### ISSUE TITLE
Will this work with GitHub Pages?

### ISSUE THREAD

**Issue by adishavit** [awood/hawkins#10]
Will this work with static sites served by GitHub pages?

**Comment by awood** [comment]
It will work when you are previewing your site [locally](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/), but not when running on GitHub.  GitHub pages has a [whitelist](https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb) of approved plugins and Hawkins isn't on that list.

To be honest, it wouldn't really be very useful to run Hawkins on GitHub pages since what's being served by GitHub pages is generally speaking going to be your final draft.  Hawkins is more geared towards the writing process when you're making lots of changes and you want to see them in the browser quickly so you can keep writing.
