### ISSUE TITLE
post command results in limited post configuration

### ISSUE THREAD

**Issue by cori** [awood/hawkins#4]
as noted in https://talk.jekyllrb.com/t/a-tool-for-automatic-browser-refreshes/2150/7, the `post` command creates a new post file with the correct title and filename, but it's missing some of the basic yaml front-matter, specifically the layout entry that styles the post as a post (and therefore loads the rest of the site style as well as the liveserver js if running under the `liveserver` command.

Perhaps this is intended behavior, and not hard to fix once the problem is understood, though.

**Comment by awood** [comment]
The reason I left a really stripped down front-matter section is because it's hard to know what users are going to want in there.  For example, on the site I run, our posts layout is called "news".  "post" is the convention and probably what 90% of people use so I'll go ahead and merge #5 but in the future I'm thinking that maybe I should look in `_config.yml` for a Hawkins section and base the frontmatter template on values from that section.

**Comment by cori** [comment]
Yep that makes a lot of sense. possible opportunity for additional switches for the post command, but that could get messy.  Thanks!

Don't know if you're interested in additional PRs for additional stuff like the TODOs in https://github.com/awood/hawkins/commit/013f73ff808abf4de739512ce5ffca6660d309ad or not - if this is really a personal project I'll stay out of your way in the future.

**Comment by awood** [comment]
Any contribution is welcome!
